; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File para ESP32 (ESP-IDF)
; Adaptado desde el proyecto original de Bluepill

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200

build_flags = 
    -Wall
    -Wextra
    ; Mantenemos la carpeta de headers si la usas, aunque ESP-IDF prefiere 'include'
    -I src
    ; Generar el mapa de memoria (útil para ver el uso de la Flash/RAM)
    -Wl,-Map=firmware.map

; Opciones de carga (por defecto usa el puerto USB-Serie detectado)
; Si usas un programador externo como ESP-Prog, descomenta la siguiente línea:
; upload_protocol = esp-prog